# Generated by Django 6.0.7 on 2026-08-07 02:15

import apps.schools.models
import django.core.validators
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='domain_address',
            field=apps.schools.models.SchoolDomainField(blank=True, db_index=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_domain_address', flags=re.RegexFlag['IGNORECASE'], message='Ingresa un dominio institucional válido (ej. ut-tijuana.edu.mx). Sin @, sin espacios y con al menos un punto.', regex='^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)+$')]),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['domain_address'], name='schools_domain_address_idx'),
        ),
    ]
