services:
  postgres:
    image: postgres:16
    container_name: cooffy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cooffy}
      POSTGRES_USER: ${POSTGRES_USER:-cooffy-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cooffy-password}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: