# Generated by Django 6.0.7 on 2026-08-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
