# Generated by Django 6.0.7 on 2026-08-06 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_accepting_orders'),
        ('schools', '0001_initial'),
        ('users', '0002_user_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='school_id',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school'),
        ),
    ]
