name: Task
description: Tarea de desarrollo para un RF
title: "Nombre"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Completa la información necesaria para realizar la tarea.

  - type: textarea
    id: objective
    attributes:
      label: Objetivo
      description: ¿Qué debe quedar implementado?
      placeholder: >
        Implementar el endpoint POST /auth/login para autenticar usuarios.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notas
      description: Información adicional, dependencias o comentarios.
      placeholder: |
        Depende de RF-01, No se fva a implementar todo en el MVP, etc
