# Generated by Django 6.0.7 on 2026-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'En espera'), ('preparing', 'En preparación'), ('ready', 'Listo para entregar'), ('picked_up', 'Entregado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_number', 'date', 'branch_id'), name='unique_order_number_per_branch_date'),
        ),
    ]
