# Generated by Django 6.0.7 on 2026-08-12 07:31

import django.db.models.deletion
from django.db import migrations, models

PAYMENT_METHODS = [
    {"id": 1, "name": "Efectivo", "is_digital": False},
    {"id": 2, "name": "Tarjeta", "is_digital": True},
]


def seed_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model("orders", "PaymentMethod")
    db_alias = schema_editor.connection.alias
    for item in PAYMENT_METHODS:
        PaymentMethod.objects.using(db_alias).get_or_create(
            pk=item["id"],
            defaults={"name": item["name"], "is_digital": item["is_digital"]},
        )


def map_payment_method_to_fk(apps, schema_editor):
    """Convierte los valores 'cash'/'card' del campo anterior a los ids 1/2."""
    Order = apps.get_model("orders", "Order")
    db_alias = schema_editor.connection.alias
    mapping = {"cash": 1, "card": 2}
    for old_value, new_id in mapping.items():
        Order.objects.using(db_alias).filter(payment_method=old_value).update(
            payment_method=new_id
        )
    Order.objects.using(db_alias).exclude(payment_method__in=[1, 2]).update(
        payment_method=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_updated_at_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_digital', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_payment_methods, migrations.RunPython.noop),
        migrations.RunPython(map_payment_method_to_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.paymentmethod'),
        ),
    ]
