# Generated by Django 6.0.7 on 2026-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentmethod_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'En espera'), ('preparing', 'En preparación'), ('ready', 'Listo para entregar'), ('picked_up', 'Entregado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
