# Generated by Django 6.0.7 on 2026-07-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_company_352c8e_idx',
            old_name='branches_company_5f1e15_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_school__57be82_idx',
            old_name='branches_school__6d0f3f_idx',
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, max_length=2048, null=True, upload_to='branches/'),
        ),
    ]
