# Generated by Django 6.0.7 on 2026-07-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
