# Generated by Django 6.0.7 on 2026-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_companyschool_branch_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
