# Generated by Django 6.0.7 on 2026-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_accepting_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='max_anticipation_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='branch',
            name='min_anticipation_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
