# Generated by Django 6.0.7 on 2026-07-21 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('max_per_order', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modifiers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_gt_0'), models.CheckConstraint(condition=models.Q(('max_per_order__gt', 0), ('max_per_order__isnull', True), _connector='OR'), name='max_per_order_gt_0_or_null')],
            },
        ),
    ]
