# Generated by Django 6.0.7 on 2026-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=2048, null=True, upload_to='products/'),
        ),
    ]
