# Generated by Django 6.0.7 on 2026-08-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_accepting_orders'),
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('stock', models.IntegerField(choices=[(-1, 'Sin stock activado'), (0, 'Sin stock'), (1, 'Con stock')], default=-1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('branch_id', 'product_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='products.product')),
            ],
            options={
                'db_table': 'product_stocks',
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__in', [-1, 0, 1])), name='product_stock_valid_state')],
            },
        ),
    ]
