// Datos de ejemplo del menú. Más adelante van a venir del backend.

export const CATEGORIES = [
  { id: "todos", name: "Todos" },
  { id: "desayuno", name: "Desayuno" },
  { id: "comida", name: "Comida" },
  { id: "snacks", name: "Snacks" },
  { id: "postres", name: "Postres" },
  { id: "bebidas", name: "Bebidas" },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Chilaquiles verdes",
    price: 45,
    description: "Totopos bañados en salsa verde, con pollo deshebrado y crema.",
    category: "desayuno",
    tag: "Favorito",
    image: "",
  },
  {
    id: 2,
    name: "Hot cakes",
    price: 35,
    description: "Tres hot cakes esponjosos con miel y mantequilla.",
    category: "desayuno",
    tag: "Clásico",
    image: "",
  },
  {
    id: 3,
    name: "Torta de milanesa",
    price: 55,
    description: "Milanesa de pollo empanizada, con jitomate, lechuga y aguacate.",
    category: "comida",
    tag: "Más pedido",
    image: "",
  },
  {
    id: 4,
    name: "Ensalada de pollo",
    price: 60,
    description: "Pechuga a la plancha, mezcla de lechugas, jitomate cherry y vinagreta.",
    category: "comida",
    tag: "Ligero",
    image: "",
  },
  {
    id: 5,
    name: "Papas gajo",
    price: 30,
    description: "Porción de papas gajo horneadas con especias, salsa incluida.",
    category: "snacks",
    tag: "Para compartir",
    image: "",
  },
  {
    id: 6,
    name: "Gelatina de mosaico",
    price: 20,
    description: "Gelatina casera de varios sabores, en vasito individual.",
    category: "postres",
    tag: "Casero",
    image: "",
  },
  {
    id: 7,
    name: "Café americano",
    price: 25,
    description: "Café de grano recién preparado, disponible caliente o frío.",
    category: "bebidas",
    tag: "Recomendado",
    image: "",
  },
  {
    id: 8,
    name: "Agua fresca de horchata",
    price: 20,
    description: "Preparada en casa cada mañana, sin conservadores.",
    category: "bebidas",
    tag: "Natural",
    image: "",
  },
];
